- Bug, on_except
- meter más doc en paquete, documentando backend
- Meter soporte redirección puertos
- mejorar comprobación de redes/mascaras
- chequear si esta el firmware y chequear si el USB esta conectado
- Configurar ethernets
- Ayuda explicando monopuesto, etc...
- Empaquetar /etc/hotplug/usb/speedtch
- Terminar sysbackend
- Bug, cuando se ejecuta como root:
Traceback (most recent call last):
  File "/usr/bin/bb-assist", line 1002, in on_buttonSaveLogs_clicked
    os.setegid(int(os.environ['SUDO_GID']))
  File "/usr/lib/python2.4/UserDict.py", line 17, in __getitem__
    def __getitem__(self, key): return self.data[key]
KeyError: 'SUDO_GID'
